studentID = int(input('Enter your 6 digit Student Identification Number:'))
F_name = input('Please Enter your First Name:')
L_name = input('Please Enter your Last Name:')
Age = int(input('What is your age?'))
Student_Addy = (input('Please Enter your full street address:'))
Phone_Num = int(input('Please enter a 10 digit phone number:'))
